version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: build/local/api/Dockerfile
    container_name: api
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - build/local/api/hosted-pg.env
    ports:
      - 5000:5000
    volumes:
      - .:/app:z
    command: /start.sh
    networks:
      - stuhub-api

  redis:
    build:
      context: .
      dockerfile: build/local/redis/Dockerfile
    container_name: redis-cache
    env_file:
      - build/local/redis/.env
    command: redis-server --save 20 1 --loglevel warning --requirepass stuhub
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 10s
      timeout: 5s
      retries: 2
    volumes:
      - local_redis_data:/root/redis
    networks:
      - stuhub-api

networks:
  stuhub-api:
    driver: bridge

volumes:
  local_redis_data: {}
