// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDocument = "documents"

// Document mapped from table <documents>
type Document struct {
	Pkid        int64     `gorm:"column:pkid;type:bigint;primaryKey;autoIncrement:true" json:"pkid"`
	PagePkid    int64     `gorm:"column:page_pkid;type:bigint;not null" json:"page_pkid"`
	Content     string    `gorm:"column:content;type:text;not null" json:"content"`
	JSONContent *string   `gorm:"column:json_content;type:json" json:"json_content"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
}

// TableName Document's table name
func (*Document) TableName() string {
	return TableNameDocument
}
