// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrganizationInvite = "organization_invites"

// OrganizationInvite mapped from table <organization_invites>
type OrganizationInvite struct {
	Pkid             int64     `gorm:"column:pkid;type:bigint;primaryKey;autoIncrement:true" json:"pkid"`
	ID               string    `gorm:"column:id;type:uuid;not null;index:idx_invite_pkid,priority:1;default:uuid_generate_v4()" json:"id"`
	OrganizationPkid int64     `gorm:"column:organization_pkid;type:bigint;not null" json:"organization_pkid"`
	UserPkid         int64     `gorm:"column:user_pkid;type:bigint;not null" json:"user_pkid"`
	CreatedAt        time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	ExpiredAt        time.Time `gorm:"column:expired_at;type:timestamp with time zone;not null" json:"expired_at"`
	IsUsed           bool      `gorm:"column:is_used;type:boolean;not null" json:"is_used"`
}

// TableName OrganizationInvite's table name
func (*OrganizationInvite) TableName() string {
	return TableNameOrganizationInvite
}
