// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSpace = "spaces"

// Space mapped from table <spaces>
type Space struct {
	Pkid        int64     `gorm:"column:pkid;type:bigint;primaryKey;autoIncrement:true" json:"pkid"`
	ID          string    `gorm:"column:id;type:uuid;not null;default:uuid_generate_v4()" json:"id"`
	OrgPkid     int64     `gorm:"column:org_pkid;type:bigint;not null" json:"org_pkid"`
	Name        string    `gorm:"column:name;type:character varying(255);not null" json:"name"`
	Description string    `gorm:"column:description;type:text;not null" json:"description"`
	IsPrivate   bool      `gorm:"column:is_private;type:boolean;not null" json:"is_private"`
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName Space's table name
func (*Space) TableName() string {
	return TableNameSpace
}
