// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	Pkid        int64      `gorm:"column:pkid;type:bigint;primaryKey;autoIncrement:true" json:"pkid"`
	ID          string     `gorm:"column:id;type:uuid;not null;default:uuid_generate_v4()" json:"id"`
	Email       string     `gorm:"column:email;type:character varying(255);not null" json:"email"`
	Password    *string    `gorm:"column:password;type:character varying(128)" json:"password"`
	FirstName   string     `gorm:"column:first_name;type:character varying(255);not null" json:"first_name"`
	LastName    string     `gorm:"column:last_name;type:character varying(255);not null" json:"last_name"`
	Avatar      string     `gorm:"column:avatar;type:character varying;not null" json:"avatar"`
	OauthGmail  string     `gorm:"column:oauth_gmail;type:character varying;not null" json:"oauth_gmail"`
	Salt        string     `gorm:"column:salt;type:character varying(255);not null" json:"salt"`
	ActivatedAt *time.Time `gorm:"column:activated_at;type:timestamp with time zone" json:"activated_at"`
	CreatedAt   time.Time  `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time  `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
